/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: mwJf7vIwKRcj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicAdvertorial.module.css"; // plasmic-import: mwJf7vIwKRcj/css

import DotSvgIcon from "./icons/PlasmicIcon__DotSvg"; // plasmic-import: MOshPqjEhwKE/icon
import StarSvgrepoComSvgIcon from "./icons/PlasmicIcon__StarSvgrepoComSvg"; // plasmic-import: 582rzEIEG-6Y/icon

createPlasmicElementProxy;

export type PlasmicAdvertorial__VariantMembers = {};
export type PlasmicAdvertorial__VariantsArgs = {};
type VariantPropType = keyof PlasmicAdvertorial__VariantsArgs;
export const PlasmicAdvertorial__VariantProps = new Array<VariantPropType>();

export type PlasmicAdvertorial__ArgsType = {};
type ArgPropType = keyof PlasmicAdvertorial__ArgsType;
export const PlasmicAdvertorial__ArgProps = new Array<ArgPropType>();

export type PlasmicAdvertorial__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultAdvertorialProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAdvertorial__RenderFunc(props: {
  variants: PlasmicAdvertorial__VariantsArgs;
  args: PlasmicAdvertorial__ArgsType;
  overrides: PlasmicAdvertorial__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__x4Id
        )}
      >
        {"Sanitize Any Surface In Seconds. No Scrubbing Required."}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__zoWsr)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__vuyuT
          )}
          onClick={async event => {
            const $steps = {};

            $steps["goToHomepage"] = true
              ? (() => {
                  const actionArgs = { destination: `/` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToHomepage"] != null &&
              typeof $steps["goToHomepage"] === "object" &&
              typeof $steps["goToHomepage"].then === "function"
            ) {
              $steps["goToHomepage"] = await $steps["goToHomepage"];
            }
          }}
        >
          <React.Fragment>
            <React.Fragment>{"Written by "}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ textDecorationLine: "underline" }}
            >
              {"nanX\u2122"}
            </span>
          </React.Fragment>
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__eEkV
          )}
        >
          {"3 minute read"}
        </div>
        <DotSvgIcon
          className={classNames(projectcss.all, sty.svg__t2ZnW)}
          role={"img"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bn71H
          )}
        >
          {"1 citation"}
        </div>
        <DotSvgIcon
          className={classNames(projectcss.all, sty.svg__p6A0)}
          role={"img"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___7D8BT
          )}
        >
          {"share"}
        </div>
      </div>
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__jZhPd)}
        displayHeight={
          hasVariant(globalVariants, "screen", "mobileOnly") ? "180px" : "350px"
        }
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"100%"}
        loading={"eager"}
        src={{
          src: "/plasmic/nan_x/images/nanXArticle1Png.png",
          fullWidth: 1020,
          fullHeight: 525,
          aspectRatio: undefined
        }}
      />

      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__p0
        )}
      >
        {
          "Billions of germs are still left behind\u2014even after wiping everything down."
        }
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___9OWdd
        )}
      >
        {"Did You Know Surface Wiping Barely Kills Anything?"}
      </div>
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__yoDyo)}
        displayHeight={
          hasVariant(globalVariants, "screen", "mobileOnly") ? "180px" : "350px"
        }
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"100%"}
        loading={"eager"}
        src={{
          src: "/plasmic/nan_x/images/nanXArticle2Png.png",
          fullWidth: 1020,
          fullHeight: 525,
          aspectRatio: undefined
        }}
      />

      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__pVg5K
        )}
      >
        <React.Fragment>
          <React.Fragment>
            {
              "So instead of relying on chemical-heavy cleaners and wiping every surface by hand\u2026\n\nYou can simply "
            }
          </React.Fragment>
          <span
            className={"plasmic_default__all plasmic_default__span"}
            style={{ fontWeight: 700 }}
          >
            {"mist"}
          </span>
          <React.Fragment>
            {
              " your surfaces \u2014 not scrub them \u2014 using a powerful disinfecting solution made from ingredients already in your medicine cabinet.\n\nNo scrubbing.\nNo toxic fumes.\nNo sticky residue.\n\nJust mist.\nAnd done."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__ckeSm)}
        displayHeight={
          hasVariant(globalVariants, "screen", "mobileOnly") ? "180px" : "350px"
        }
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"100%"}
        loading={"eager"}
        src={{
          src: "/plasmic/nan_x/images/nanXArticle3Png.png",
          fullWidth: 1020,
          fullHeight: 525,
          aspectRatio: undefined
        }}
      />

      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___0AzDi
        )}
      >
        {
          "A surprisingly powerful homemade disinfectant is sitting inside your medicine cabinet."
        }
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__npEal
        )}
      >
        {"The Power of \u201cMisting\u201d Instead of Wiping"}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___11Bc9
        )}
      >
        <React.Fragment>
          <React.Fragment>{"But what do we mean by \u201c"}</React.Fragment>
          <span
            className={"plasmic_default__all plasmic_default__span"}
            style={{ fontWeight: 700 }}
          >
            {"mist"}
          </span>
          <React.Fragment>
            {"\u201d?\n\nWe\u2019re talking about using a "}
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__jv9YD
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"disinfectant spray gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {".\n\nThese devices spray an ultra-fine "}
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__tO1S5
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"NanoMist\u2122"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " \u2014 a lightweight, fast-drying mist that coats every surface evenly and reaches places wipes can\u2019t, like around handles, edges, cracks, and tight corners.\n\nPeople are using these "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__exv4J
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"spray guns"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " on kitchen counters, bathroom sinks, toilet seats and handles, door knobs, high-touch areas, and even electronics.\n\nThe mist settles, kills germs on contact, and dries almost instantly.\n\nThat means your home becomes cleaner, safer, and more thoroughly disinfected \u2014 without wiping a single thing."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <PlasmicLink__
        className={classNames(projectcss.all, projectcss.a, sty.link___273DV)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__gEAk)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "180px"
              : "350px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanX1Png.png",
            fullWidth: 1024,
            fullHeight: 1536,
            aspectRatio: undefined
          }}
        />
      </PlasmicLink__>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__jmvV
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__vnqGm
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " sanitizing a toilet\u2014obliterating germs instantly, even in tough-to-reach spots."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__mCuMl
        )}
      >
        {
          "So What Is This Powerful \u201cMedicine Cabinet\u201d Disinfectant Solution?"
        }
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__ebRF
        )}
      >
        {
          "It\u2019s surprisingly simple.\n\nYou don\u2019t need harsh cleaners.\nYou don\u2019t need bleach.\nAnd you don\u2019t need expensive store-bought sprays.\n\nAll you need is one common ingredient almost every household already has\u2026 and a little water.\n\nIt\u2019s the same ingredient nurses use, the same one parents put on cuts and scrapes, and the same one found in nearly every first-aid kit in America:"
        }
      </div>
      <PlasmicLink__
        className={classNames(projectcss.all, projectcss.a, sty.link__lQVnN)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img___878Jz)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "180px"
              : "350px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanXArticle4Png.png",
            fullWidth: 1020,
            fullHeight: 525,
            aspectRatio: undefined
          }}
        />
      </PlasmicLink__>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__ieoFq
        )}
      >
        <React.Fragment>
          <React.Fragment>{"Refilling the "}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__zveTi
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {" disinfectant reservoir\u2014free, quick, simple, and mess-free."}
          </React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__lay6W
        )}
      >
        {"The Secret? Hydrogen Peroxide."}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__mb4Rk
        )}
      >
        <React.Fragment>
          <React.Fragment>
            {
              "When mixed with water, it becomes a highly potent disinfectant that breaks down germs at the cellular level \u2014 disrupting membranes, denaturing proteins, and neutralizing harmful bacteria and viruses.\n\nStudies show hydrogen peroxide kills germs better than nearly all store-bought sprays \u2014 even the dangerous germs protected by tough layers that regular cleaners cannot penetrate.\n\nWhen this hydrogen peroxide solution is turned into an ultra-fine"
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__fyBm
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {" NanoMist\u2122"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              ", it becomes a super effective, residue-free disinfectant that instantly coats surfaces and destroys germs on contact \u2014 without scrubbing.\n\nIt\u2019s so easy you\u2019ll wonder why you spent years wiping everything by hand and wasting money on expensive store-bought disinfectant sprays."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <PlasmicLink__
        className={classNames(projectcss.all, projectcss.a, sty.link__nDd1T)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__nIayZ)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "180px"
              : "350px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanXArticle5Png.png",
            fullWidth: 1020,
            fullHeight: 525,
            aspectRatio: undefined
          }}
        />
      </PlasmicLink__>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__tyqPe
        )}
      >
        {
          "Even one missed drop of chicken juice can breed dangerous, fast-spreading bacteria."
        }
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__dJxl
        )}
      >
        {"The Real Danger of \u201cGood Enough\u201d Cleaning"}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__y2Cet
        )}
      >
        {
          "Maybe nothing\u2019s happened to you yet.\nOr maybe you\u2019ve had a close call.\n\nEither way, it only takes a single drop of raw chicken juice on your counter to spread Campylobacter \u2014 one of the leading causes of severe food-borne illness.\n\nYou can\u2019t see it.\nYou can\u2019t smell it.\nAnd wiping with a traditional disinfectant spray rarely kills it.\n\nCampylobacter is so aggressive that even a single microscopic amount left behind can spread across your surfaces \u2014 and one touch is enough to trigger days of violent food poisoning and long-term gut inflammation.\n\nAnd it\u2019s not just the kitchen.\n\nBathroom surfaces, toilet handles, sink fixtures, and high-touch areas can all harbor germs far more stubborn than most cleaners are designed to eliminate.\n\nThis is why proper disinfection matters long before you ever \u201cget sick\u201d \u2014 and it\u2019s even more important this winter, with cold and flu season in full swing."
        }
      </div>
      <PlasmicLink__
        className={classNames(projectcss.all, projectcss.a, sty.link___9C2BF)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__osmuL)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "180px"
              : "350px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanXArticle6Png.png",
            fullWidth: 1020,
            fullHeight: 525,
            aspectRatio: undefined
          }}
        />
      </PlasmicLink__>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__dekDp
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__tSXqe
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " rapidly sanitizing a kitchen sink\u2014killing germs on contact."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__fasM2
        )}
      >
        {
          "So What\u2019s the Best Way to Spray the Hydrogen Peroxide (or Alcohol) Solution?"
        }
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__kIgrH
        )}
      >
        <React.Fragment>
          <React.Fragment>
            {
              "While this homemade disinfectant is incredibly potent, how you apply it matters just as much.\n\nSure, you could pour it into a spray bottle \u2014 but a basic spray bottle requires endless, tiring hand-pumping, and it can only shoot heavy droplets, which means uneven coverage and germs left behind.\n\nThis is why professional cleaners use "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__t1D7J
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"disinfectant spray guns"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " \u2014 devices that turn liquid into an ultra-fine mist so surfaces get coated quickly, evenly, and completely.\n\nAnd for the first time ever, you can get an "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__ivgbb
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"industrial-grade spray gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " designed for home use\u2026 \n\nOne that actually produces a real "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link___8WZMn
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"NanoMist\u2122"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              ", not the weak, sputtering fog you see from cheap knockoffs.\n\nThe "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__utQ
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Disinfectant Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " is engineered to blanket surfaces with an ultra-fine, perfectly even NanoMist\u2122 \u2014 reaching corners and crevices traditional spraying simply can\u2019t.\n\nIt runs for hours on a single charge, feels solid in the hand, and is built to last.\n\nAnd unlike the cheap versions, the "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__fHv3
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {" comes with a lifetime warranty \u2014 so you only buy it once."}
          </React.Fragment>
        </React.Fragment>
      </div>
      <PlasmicLink__
        className={classNames(projectcss.all, projectcss.a, sty.link__r7EmP)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img___83EEb)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "180px"
              : "350px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanX3Jpg.jpg",
            fullWidth: 1500,
            fullHeight: 1500,
            aspectRatio: undefined
          }}
        />
      </PlasmicLink__>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___0XsBb
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__gJqMh
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " can be used everywhere\u2014on virtually anything you want to sanitize."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__qgSUl
        )}
      >
        {"And There\u2019s Never Been a Better Time to Get One"}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__vRfGf
        )}
      >
        <React.Fragment>
          <React.Fragment>{"Our "}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__uzYR
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"Black Friday"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " event just went live \u2014 and the deal is honestly unbelievable.\n\nFor a very limited time, you can claim a free "
            }
          </React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__fGkB
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"nanX\u2122 Spray Gun"}
            </PlasmicLink__>
          }
          <React.Fragment>
            {
              " as part of our biggest holiday promotion of the year.\n\nNo gimmicks.\nNo hoops to jump through.\nNot even shipping costs.\n\nIt\u2019s the kind of offer people wait all year for \u2014 and once it\u2019s gone, it\u2019s gone."
            }
          </React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__yFliB
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.link__mooKe
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              {"\ud83d\udc49  Claim Free Spray Gun Here  \ud83d\udc48"}
            </PlasmicLink__>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__pVclo
        )}
      >
        {"All Orders Ship Free"}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__xjBw)}>
        <PlasmicLink__
          className={classNames(projectcss.all, projectcss.a, sty.link__mvToA)}
          component={Link}
          href={`/`}
          platform={"nextjs"}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__nKaHs
            )}
          >
            {"Get Offer"}
          </div>
        </PlasmicLink__>
        <div className={classNames(projectcss.all, sty.freeBox__cOe0I)} />

        <div className={classNames(projectcss.all, sty.freeBox__kv1Fs)}>
          <div className={classNames(projectcss.all, sty.freeBox___3Aq8J)}>
            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg___3Na7Z)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__byVpB)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg___9Jagr)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg___6AsF)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__wik1X)}
              role={"img"}
            />
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___564Z
            )}
          >
            {"Black Friday Offer"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__mnKM
            )}
          >
            {"In Stock - Ships Now"}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAdvertorial__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAdvertorial__VariantsArgs;
    args?: PlasmicAdvertorial__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAdvertorial__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAdvertorial__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAdvertorial__ArgProps,
          internalVariantPropNames: PlasmicAdvertorial__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAdvertorial__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdvertorial";
  } else {
    func.displayName = `PlasmicAdvertorial.${nodeName}`;
  }
  return func;
}

export const PlasmicAdvertorial = Object.assign(
  // Top-level PlasmicAdvertorial renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAdvertorial
    internalVariantProps: PlasmicAdvertorial__VariantProps,
    internalArgProps: PlasmicAdvertorial__ArgProps
  }
);

export default PlasmicAdvertorial;
/* prettier-ignore-end */
