/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: lXMRAHw96I_T

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicReturns.module.css"; // plasmic-import: lXMRAHw96I_T/css

createPlasmicElementProxy;

export type PlasmicReturns__VariantMembers = {};
export type PlasmicReturns__VariantsArgs = {};
type VariantPropType = keyof PlasmicReturns__VariantsArgs;
export const PlasmicReturns__VariantProps = new Array<VariantPropType>();

export type PlasmicReturns__ArgsType = {};
type ArgPropType = keyof PlasmicReturns__ArgsType;
export const PlasmicReturns__ArgProps = new Array<ArgPropType>();

export type PlasmicReturns__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultReturnsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReturns__RenderFunc(props: {
  variants: PlasmicReturns__VariantsArgs;
  args: PlasmicReturns__ArgsType;
  overrides: PlasmicReturns__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicReturns.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicReturns.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicReturns.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicReturns.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicReturns.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicReturns.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__wdGvm)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xtCRw
              )}
            >
              {"Return & Warranty Policy"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tMzr8
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Last updated"}
                </span>
                <React.Fragment>{": November 12, 2025"}</React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__srIm0
              )}
            >
              {"At nanX, your satisfaction is our priority."}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___2CBb1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__urkkg
                )}
              >
                {"Returns"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dM3
                )}
              >
                {
                  "We offer a no-questions-asked, 30-day money-back guarantee from the date of delivery. Returns are refunded in full, minus the cost of your prepaid shipping label and a $4.95 handling and restocking fee. To start a return, contact support@nanXclean.com from the same email used at purchase."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bd7FQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ctvZi
                )}
              >
                {"Lifetime Warranty"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kx7Zn
                )}
              >
                {
                  "If you purchased the Lifetime Warranty Add-On ($9.95), you can request a replacement anytime by contacting nanX from the same email used at purchase. We\u2019ll send a prepaid return label, and once the product is received, a new replacement will be issued at no additional cost. The original item must be returned for the warranty to apply."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__wc7Xk)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hxyWl
                )}
              >
                {"Contact"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4O83
                )}
              >
                {
                  "For any questions about this Privacy Policy, please contact:\nnanX\n299 Woodbridge Drive\nMount Airy, NC 27030\nEmail: support@nanXclean.com"
                }
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "footer"],
  announcement: ["announcement"],
  nav: ["nav"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReturns__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReturns__VariantsArgs;
    args?: PlasmicReturns__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicReturns__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicReturns__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReturns__ArgProps,
          internalVariantPropNames: PlasmicReturns__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReturns__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicReturns";
  } else {
    func.displayName = `PlasmicReturns.${nodeName}`;
  }
  return func;
}

export const PlasmicReturns = Object.assign(
  // Top-level PlasmicReturns renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicReturns
    internalVariantProps: PlasmicReturns__VariantProps,
    internalArgProps: PlasmicReturns__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Return & Warranty Policy | nanX™",
      description:
        "Every order is backed by a 30-day, no-questions-asked money-back guarantee—and an optional lifetime warranty for lasting protection.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicReturns;
/* prettier-ignore-end */
