/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: fBRhan40XBYT

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicPrivacy.module.css"; // plasmic-import: fBRhan40XBYT/css

createPlasmicElementProxy;

export type PlasmicPrivacy__VariantMembers = {};
export type PlasmicPrivacy__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrivacy__VariantsArgs;
export const PlasmicPrivacy__VariantProps = new Array<VariantPropType>();

export type PlasmicPrivacy__ArgsType = {};
type ArgPropType = keyof PlasmicPrivacy__ArgsType;
export const PlasmicPrivacy__ArgProps = new Array<ArgPropType>();

export type PlasmicPrivacy__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultPrivacyProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPrivacy__RenderFunc(props: {
  variants: PlasmicPrivacy__VariantsArgs;
  args: PlasmicPrivacy__ArgsType;
  overrides: PlasmicPrivacy__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicPrivacy.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPrivacy.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPrivacy.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicPrivacy.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicPrivacy.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicPrivacy.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicPrivacy.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicPrivacy.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox___3I5Ts)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__y1A3F
              )}
            >
              {"Privacy Policy"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rrcRs
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Last updated"}
                </span>
                <React.Fragment>{": November 12, 2025"}</React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b9Vke
              )}
            >
              {
                "At nanX, your privacy matters. This Privacy Policy explains how we collect, use, and protect your information when you interact with our website at nanXclean.com."
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__wVnrb)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__npLM
                )}
              >
                {"Information We Collect"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9QWnv
                )}
              >
                {
                  "We collect information you provide through forms on our website or Meta lead forms, such as your name, email address, and phone number. This information helps us respond to your inquiries, fulfill orders, and provide updates about our products."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mqFbm)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7Mu5
                )}
              >
                {"Payments"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__f8QRg
                )}
              >
                {
                  "We do not store or process your payment information directly. All payments are securely handled by third-party providers such as Stripe and Chargebee, which comply with industry standards for data security and encryption."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__hdBdo)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__chHoz
                )}
              >
                {"How We Use Your Information"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__a94R7
                )}
              >
                {
                  "We use your information to:\n1) Process and fulfill your requests or orders\n2) Communicate about updates, offers, or support\n3) Improve our website and customer experience"
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xina7)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5MZfi
                )}
              >
                {"Information Sharing"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aojlX
                )}
              >
                {
                  "We do not sell, rent, or share your personal information with third parties, except as necessary to process payments or provide requested services."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fzbMe)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lxty0
                )}
              >
                {"Data Security"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pZkIj
                )}
              >
                {
                  "We implement reasonable technical and organizational measures to protect your information from unauthorized access or disclosure."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___11Fsm)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uqk0C
                )}
              >
                {"Your Rights"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5M1Ze
                )}
              >
                {
                  "You can request to view, update, or delete your personal information at any time by contacting us at support@nanXclean.com."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ddDFw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wkL6
                )}
              >
                {"Contact"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tKNy
                )}
              >
                {
                  "For any questions about this Privacy Policy, please contact:\nnanX\n299 Woodbridge Drive\nMount Airy, NC 27030\nEmail: support@nanXclean.com"
                }
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "footer"],
  announcement: ["announcement"],
  nav: ["nav"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrivacy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrivacy__VariantsArgs;
    args?: PlasmicPrivacy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPrivacy__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPrivacy__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrivacy__ArgProps,
          internalVariantPropNames: PlasmicPrivacy__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrivacy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrivacy";
  } else {
    func.displayName = `PlasmicPrivacy.${nodeName}`;
  }
  return func;
}

export const PlasmicPrivacy = Object.assign(
  // Top-level PlasmicPrivacy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicPrivacy
    internalVariantProps: PlasmicPrivacy__VariantProps,
    internalArgProps: PlasmicPrivacy__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Privacy Policy | nanX™",
      description:
        "Learn how nanX™ protects your data. We never sell or share your information and use secure payment processing.",
      ogImageSrc:
        "https://site-assets.plasmic.app/20e233b0acb6b6c934cd365980f2ab84.png",
      canonical: ""
    }
  }
);

export default PlasmicPrivacy;
/* prettier-ignore-end */
