/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: uogUMQBXCRRV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Pdp from "../../Pdp"; // plasmic-import: 8MpFhDHD96MB/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicDiscover.module.css"; // plasmic-import: uogUMQBXCRRV/css

createPlasmicElementProxy;

export type PlasmicDiscover__VariantMembers = {};
export type PlasmicDiscover__VariantsArgs = {};
type VariantPropType = keyof PlasmicDiscover__VariantsArgs;
export const PlasmicDiscover__VariantProps = new Array<VariantPropType>();

export type PlasmicDiscover__ArgsType = {};
type ArgPropType = keyof PlasmicDiscover__ArgsType;
export const PlasmicDiscover__ArgProps = new Array<ArgPropType>();

export type PlasmicDiscover__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  pdp?: Flex__<typeof Pdp>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultDiscoverProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDiscover__RenderFunc(props: {
  variants: PlasmicDiscover__VariantsArgs;
  args: PlasmicDiscover__ArgsType;
  overrides: PlasmicDiscover__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicDiscover.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDiscover.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDiscover.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicDiscover.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicDiscover.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicDiscover.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <Pdp
            data-plasmic-name={"pdp"}
            data-plasmic-override={overrides.pdp}
            className={classNames("__wab_instance", sty.pdp)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "pdp", "footer"],
  announcement: ["announcement"],
  nav: ["nav"],
  pdp: ["pdp"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  pdp: typeof Pdp;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDiscover__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDiscover__VariantsArgs;
    args?: PlasmicDiscover__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDiscover__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDiscover__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDiscover__ArgProps,
          internalVariantPropNames: PlasmicDiscover__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDiscover__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDiscover";
  } else {
    func.displayName = `PlasmicDiscover.${nodeName}`;
  }
  return func;
}

export const PlasmicDiscover = Object.assign(
  // Top-level PlasmicDiscover renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    pdp: makeNodeComponent("pdp"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicDiscover
    internalVariantProps: PlasmicDiscover__VariantProps,
    internalArgProps: PlasmicDiscover__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Disinfectant Spray Gun | nanX™",
      description:
        "The cordless nanX® Spray Gun eliminates germs on contact—without soaking surfaces or leaving residue. Clean smarter with NanoMist™ technology.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDiscover;
/* prettier-ignore-end */
