/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: 7oFtnP1VA9G_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicConfirmation.module.css"; // plasmic-import: 7oFtnP1VA9G_/css

import BagSvgIcon from "./icons/PlasmicIcon__BagSvg"; // plasmic-import: bSpVB1kOekDy/icon

createPlasmicElementProxy;

export type PlasmicConfirmation__VariantMembers = {};
export type PlasmicConfirmation__VariantsArgs = {};
type VariantPropType = keyof PlasmicConfirmation__VariantsArgs;
export const PlasmicConfirmation__VariantProps = new Array<VariantPropType>();

export type PlasmicConfirmation__ArgsType = {};
type ArgPropType = keyof PlasmicConfirmation__ArgsType;
export const PlasmicConfirmation__ArgProps = new Array<ArgPropType>();

export type PlasmicConfirmation__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  svg?: Flex__<"svg">;
  footer?: Flex__<typeof Footer>;
  metaPixel?: Flex__<typeof Embed>;
};

export interface DefaultConfirmationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicConfirmation__RenderFunc(props: {
  variants: PlasmicConfirmation__VariantsArgs;
  args: PlasmicConfirmation__ArgsType;
  overrides: PlasmicConfirmation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicConfirmation.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicConfirmation.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicConfirmation.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicConfirmation.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicConfirmation.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicConfirmation.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicConfirmation.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicConfirmation.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__dy6Hi)}>
            <BagSvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nCdeC
              )}
            >
              {"Thank you!"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__s2XEa
              )}
            >
              {
                "We've received your order! \n\nShipping with tracking will be emailed to you soon. \n\nFor any questions, please email us at: support@nanXclean.com"
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__t1GvA)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uPce
                )}
              >
                {"Contact"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gsFrJ
                )}
              >
                {
                  "For any questions, please email us at: \n\nsupport@nanXclean.com"
                }
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          <Embed
            data-plasmic-name={"metaPixel"}
            data-plasmic-override={overrides.metaPixel}
            className={classNames("__wab_instance", sty.metaPixel)}
            code={
              "\n\n<!-- Meta Pixel Code -->\n<script>\n!function(f,b,e,v,n,t,s)\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\nn.queue=[];t=b.createElement(e);t.async=!0;\nt.src=v;s=b.getElementsByTagName(e)[0];\ns.parentNode.insertBefore(t,s)}(window, document,'script',\n'https://connect.facebook.net/en_US/fbevents.js');\nfbq('init', '819736280774420');\nfbq('track', 'PageView');      // Standard pageview event\nfbq('track', 'Purchase');   // Fires when viewing a product or key page\n</script>\n<noscript><img height=\"1\" width=\"1\" style=\"display:none\"\nsrc=\"https://www.facebook.com/tr?id=819736280774420&ev=PageView&noscript=1\"\n/></noscript>\n<!-- End Meta Pixel Code -->\n\n"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "svg", "footer", "metaPixel"],
  announcement: ["announcement"],
  nav: ["nav"],
  svg: ["svg"],
  footer: ["footer"],
  metaPixel: ["metaPixel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  svg: "svg";
  footer: typeof Footer;
  metaPixel: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicConfirmation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicConfirmation__VariantsArgs;
    args?: PlasmicConfirmation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicConfirmation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicConfirmation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicConfirmation__ArgProps,
          internalVariantPropNames: PlasmicConfirmation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicConfirmation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConfirmation";
  } else {
    func.displayName = `PlasmicConfirmation.${nodeName}`;
  }
  return func;
}

export const PlasmicConfirmation = Object.assign(
  // Top-level PlasmicConfirmation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    metaPixel: makeNodeComponent("metaPixel"),

    // Metadata about props expected for PlasmicConfirmation
    internalVariantProps: PlasmicConfirmation__VariantProps,
    internalArgProps: PlasmicConfirmation__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Order Confirmation | nanX™",
      description: "Thank you for placing an order with nanX™.",
      ogImageSrc:
        "https://site-assets.plasmic.app/20e233b0acb6b6c934cd365980f2ab84.png",
      canonical: ""
    }
  }
);

export default PlasmicConfirmation;
/* prettier-ignore-end */
