/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: vaodl733Yf-C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicTerms.module.css"; // plasmic-import: vaodl733Yf-C/css

createPlasmicElementProxy;

export type PlasmicTerms__VariantMembers = {};
export type PlasmicTerms__VariantsArgs = {};
type VariantPropType = keyof PlasmicTerms__VariantsArgs;
export const PlasmicTerms__VariantProps = new Array<VariantPropType>();

export type PlasmicTerms__ArgsType = {};
type ArgPropType = keyof PlasmicTerms__ArgsType;
export const PlasmicTerms__ArgProps = new Array<ArgPropType>();

export type PlasmicTerms__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultTermsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTerms__RenderFunc(props: {
  variants: PlasmicTerms__VariantsArgs;
  args: PlasmicTerms__ArgsType;
  overrides: PlasmicTerms__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicTerms.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicTerms.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicTerms.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicTerms.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicTerms.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicTerms.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__pK6)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uhEv
              )}
            >
              {"Terms of Service"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b7Qa
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Last updated"}
                </span>
                <React.Fragment>{": November 12, 2025"}</React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vk0Uj
              )}
            >
              {
                "Welcome to nanX. By accessing or purchasing from nanXclean.com, you agree to the following terms and conditions."
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__lQxQr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cTuX
                )}
              >
                {"1. General"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9SaDi
                )}
              >
                {
                  "These Terms of Service govern your use of our website and the purchase of our products. By using our site, you confirm that you are at least 18 years old or have permission from a legal guardian."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___1CxCd)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pzSj
                )}
              >
                {"2. Products and Orders"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__agbIe
                )}
              >
                {
                  "We strive to ensure all product descriptions, pricing, and availability are accurate. However, we reserve the right to correct any errors or update product details at any time without notice. All orders are subject to acceptance and product availability."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__pWtqj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mdPyo
                )}
              >
                {"3. Payments"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zDibB
                )}
              >
                {
                  "Payments are processed securely through Stripe and Chargebee. We do not store or have access to your payment information."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ctElV)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jGhY
                )}
              >
                {"4. Shipping and Returns"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gg93X
                )}
              >
                {
                  "We aim to process orders promptly. Shipping times may vary depending on your location. If you are not satisfied with your purchase, please contact support@nanXclean.com within 30 days for return or exchange options."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__d3YwG)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wZhZn
                )}
              >
                {"5. Intellectual Property"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sNuCp
                )}
              >
                {
                  "All content on this site \u2014 including text, graphics, and images \u2014 is owned by or licensed to nanX. You may not copy, distribute, or reproduce any part of this website without prior written consent."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__qupQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gCrGj
                )}
              >
                {"6. Limitation of Liability"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zLw1
                )}
              >
                {
                  "To the fullest extent permitted by law, nanX is not liable for any indirect, incidental, or consequential damages arising from the use or inability to use our products or website."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__aidDh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rMn3H
                )}
              >
                {"7. Privacy"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iwvbv
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {"Your privacy is important to us. Please refer to our "}
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link
                      )}
                      component={Link}
                      href={"https://nanxclean.com/privacy"}
                      platform={"nextjs"}
                    >
                      {"Privacy Policy"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>
                    {" for details on how we handle your information."}
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mBilt)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sbewo
                )}
              >
                {"8. Contact"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pgDnm
                )}
              >
                {
                  "For any questions about this Privacy Policy, please contact:\nnanX\n299 Woodbridge Drive\nMount Airy, NC 27030\nEmail: support@nanXclean.com"
                }
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "link", "footer"],
  announcement: ["announcement"],
  nav: ["nav"],
  link: ["link"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  link: "a";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTerms__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTerms__VariantsArgs;
    args?: PlasmicTerms__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTerms__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTerms__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTerms__ArgProps,
          internalVariantPropNames: PlasmicTerms__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTerms__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTerms";
  } else {
    func.displayName = `PlasmicTerms.${nodeName}`;
  }
  return func;
}

export const PlasmicTerms = Object.assign(
  // Top-level PlasmicTerms renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    link: makeNodeComponent("link"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicTerms
    internalVariantProps: PlasmicTerms__VariantProps,
    internalArgProps: PlasmicTerms__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Terms of Service | nanX™",
      description:
        "By purchasing or using our products, you agree to our standard policies and conditions.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTerms;
/* prettier-ignore-end */
