/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: dQ3Sxk4fWxOM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Announcement from "../../Announcement"; // plasmic-import: 4lO7SXttxyIT/component
import Nav from "../../Nav"; // plasmic-import: 32hGVgiLB7NT/component
import Pdp from "../../Pdp"; // plasmic-import: 8MpFhDHD96MB/component
import Footer from "../../Footer"; // plasmic-import: El0mv80Cdurv/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicNewsbreak.module.css"; // plasmic-import: dQ3Sxk4fWxOM/css

import DotSvgIcon from "./icons/PlasmicIcon__DotSvg"; // plasmic-import: MOshPqjEhwKE/icon

createPlasmicElementProxy;

export type PlasmicNewsbreak__VariantMembers = {};
export type PlasmicNewsbreak__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewsbreak__VariantsArgs;
export const PlasmicNewsbreak__VariantProps = new Array<VariantPropType>();

export type PlasmicNewsbreak__ArgsType = {};
type ArgPropType = keyof PlasmicNewsbreak__ArgsType;
export const PlasmicNewsbreak__ArgProps = new Array<ArgPropType>();

export type PlasmicNewsbreak__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<typeof Announcement>;
  nav?: Flex__<typeof Nav>;
  pdp?: Flex__<typeof Pdp>;
  footer?: Flex__<typeof Footer>;
  metaPixel?: Flex__<typeof Embed>;
};

export interface DefaultNewsbreakProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewsbreak__RenderFunc(props: {
  variants: PlasmicNewsbreak__VariantsArgs;
  args: PlasmicNewsbreak__ArgsType;
  overrides: PlasmicNewsbreak__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicNewsbreak.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicNewsbreak.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicNewsbreak.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicNewsbreak.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicNewsbreak.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicNewsbreak.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicNewsbreak.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicNewsbreak.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Announcement
            data-plasmic-name={"announcement"}
            data-plasmic-override={overrides.announcement}
            className={classNames("__wab_instance", sty.announcement)}
          />

          <Nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__lqsrN)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w82Sz
              )}
            >
              {"Sanitize Any Surface In Seconds. No Scrubbing Required."}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fvxEz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bymMd
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToHomepage"] = true
                    ? (() => {
                        const actionArgs = { destination: `/` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToHomepage"] != null &&
                    typeof $steps["goToHomepage"] === "object" &&
                    typeof $steps["goToHomepage"].then === "function"
                  ) {
                    $steps["goToHomepage"] = await $steps["goToHomepage"];
                  }
                }}
              >
                <React.Fragment>
                  <React.Fragment>{"Written by "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ textDecorationLine: "underline" }}
                  >
                    {"nanX"}
                  </span>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gxCJu
                )}
              >
                {"3 minute read"}
              </div>
              <DotSvgIcon
                className={classNames(projectcss.all, sty.svg__fxXl8)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p4Yxu
                )}
              >
                {"1 citation"}
              </div>
              <DotSvgIcon
                className={classNames(projectcss.all, sty.svg___2Lghf)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tiKnM
                )}
              >
                {"share"}
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__u71BF)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "180px"
                  : "350px"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanXArticle1Png.png",
                fullWidth: 1020,
                fullHeight: 525,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xt100
              )}
            >
              {"Did You Know Surface Wiping Barely Kills Anything?"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lCLxG
              )}
            >
              {
                "And disinfectant sprays aren\u2019t just ineffective \u2014 they\u2019re toxic. \n\nThe moment you spray them, those harsh chemicals become an aerosol that pollutes the air you breathe.\n\nMost people think their current cleaning routine is \u201cgood enough,\u201d but the truth is it\u2019s slow, it worsens indoor air quality, and it still leaves behind some of the nastiest germs.\n\nNow keep reading, because what you\u2019re about to learn will completely change how you disinfect your home."
              }
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___1Lfgq)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "180px"
                  : "350px"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanXArticle2Png.png",
                fullWidth: 1020,
                fullHeight: 525,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mw1Dn
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Instead of relying on chemical-heavy cleaners and wiping every surface by hand\u2026\n\nYou can simply "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"mist"}
                </span>
                <React.Fragment>
                  {
                    " your surfaces \u2014 not scrub them \u2014 using a powerful disinfecting solution made from ingredients already in your medicine cabinet.\n\nNo scrubbing.\nNo toxic fumes.\nNo sticky residue.\n\nJust mist.\nAnd done."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___6MDz)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "180px"
                  : "350px"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanXArticle3Png.png",
                fullWidth: 1020,
                fullHeight: 525,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hnS77
              )}
            >
              {"The Power of \u201cMisting\u201d Instead of Wiping"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yd2G9
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"But what do we mean by \u201c"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"mist"}
                </span>
                <React.Fragment>
                  {"\u201d?\n\nWe\u2019re talking about using a "}
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__qv3CA
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"disinfectant spray gun"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {".\n\nThese devices spray an ultra-fine "}
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__bapXz
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"NanoMist\u2122"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    " \u2014 a lightweight, fast-drying mist that coats every surface evenly and reaches places wipes can\u2019t, like around handles, edges, cracks, and tight corners.\n\nPeople are using these "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__gJw0C
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"spray guns"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    " on kitchen counters, bathroom sinks, toilet seats and handles, door knobs, high-touch areas, and even electronics.\n\nThe mist settles, kills germs on contact, and dries almost instantly.\n\nThat means your home becomes cleaner, safer, and more thoroughly disinfected \u2014 without wiping a single thing."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__c5LIy
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__fljmZ)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "180px"
                    : "350px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nan_x/images/nanX1Png.png",
                  fullWidth: 1024,
                  fullHeight: 1536,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jvoX6
              )}
            >
              {
                "So What Is This Powerful \u201cMedicine Cabinet\u201d Disinfect Solution?"
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bdmfR
              )}
            >
              {
                "It\u2019s surprisingly simple.\n\nYou don\u2019t need harsh cleaners.\nYou don\u2019t need bleach.\nAnd you definitely don\u2019t need expensive specialty sprays.\n\nAll you need is one common disinfecting ingredient almost every household already has\u2026 and a little water.\n\nIt\u2019s the same ingredient nurses use, the same one parents put on cuts and scrapes, and the same one found in nearly every first-aid kit in America:"
              }
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___0CEcx
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__yoZr)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "180px"
                    : "350px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nan_x/images/nanXArticle4Png.png",
                  fullWidth: 1020,
                  fullHeight: 525,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oJ8Nj
              )}
            >
              {"Hydrogen Peroxide."}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rL9
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "When mixed with water, it becomes a highly potent disinfectant that breaks down germs at the cellular level \u2014 disrupting membranes, denaturing proteins, and neutralizing harmful bacteria and viruses.\n\nStudies show hydrogen peroxide outperforms many standard surface cleaners in eliminating stubborn biofilms \u2014 the protective layers that allow dangerous germs to survive traditional wiping.\n\n(Some people even use rubbing alcohol for a rapid drying option \u2014 both work incredibly well.)\n\nWhen this clean solution is turned into an ultra-fine"
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link___3QHrO
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {" NanoMist\u2122"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    ", it becomes a super effective, residue-free disinfectant that instantly coats surfaces and destroys germs \u2014 without scrubbing.\n\nIt\u2019s so easy you\u2019ll wonder why you spent years wiping everything by hand."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__lxA3
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__tuLzf)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "180px"
                    : "350px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nan_x/images/nanXArticle5Png.png",
                  fullWidth: 1020,
                  fullHeight: 525,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qrBgJ
              )}
            >
              {"The Real Danger of \u201cGood Enough\u201d Cleaning"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0VAKw
              )}
            >
              {
                "Maybe nothing\u2019s happened to you yet.\nOr maybe you\u2019ve had a close call.\n\nEither way, it only takes one single drop of raw chicken juice on your counter to spread Campylobacter \u2014 one of the leading causes of severe food-borne illness.\n\nYou can\u2019t see it.\nYou can\u2019t smell it.\nAnd wiping with a traditional disinfectant spray rarely kills it.\n\nCampylobacter is so aggressive that even a microscopic amount can trigger days of violent food poisoning, dehydration, and serious gut inflammation.\n\nAnd it\u2019s not just the kitchen.\n\nBathroom surfaces, toilet handles, sink fixtures, and high-touch areas can all harbor germs far more stubborn than most cleaners are designed to eliminate.\n\nThis is why proper disinfection matters long before you ever \u201cget sick.\u201d"
              }
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__t7Yvq
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__g2Vl5)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "180px"
                    : "350px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nan_x/images/nanXArticle6Png.png",
                  fullWidth: 1020,
                  fullHeight: 525,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7Sry3
              )}
            >
              {
                "So What\u2019s the Best Way to Spray the Hydrogen Peroxide (or Alcohol) Solution?"
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__deUa6
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "While the disinfecting mixture is incredibly potent, how you apply it matters just as much.\n\nNot all "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__jlrb4
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"spray guns"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    " are created equal.\n\nCheap knockoffs leak, sputter, and spray unevenly \u2014 leaving gaps, streaks, and untouched areas. Many don\u2019t even produce a true "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__wu7S
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"NanoMist\u2122"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    ", which means the disinfectant never fully coats the surface.\n\nThat\u2019s why thousands are switching to the "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__dzvLu
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"nanX Disinfectant Spray Gun"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    ".\n\nIt\u2019s engineered to blanket surfaces quickly with an ultra-fine, perfectly even "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__bvr8N
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"NanoMist\u2122"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    ".\n\nIt runs for hours on a single charge, feels solid in the hand, and is built to last.\n\nAnd unlike the cheap versions, the "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__rC9Vi
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"nanX Spray Gun"}
                  </PlasmicLink__>
                }
                <React.Fragment>
                  {
                    " comes with a lifetime warranty \u2014 so you only buy it once."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___8Tsk
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__v1DRn)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "180px"
                    : "350px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nan_x/images/nanX3Jpg.jpg",
                  fullWidth: 1500,
                  fullHeight: 1500,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__urfT
              )}
            >
              {"And Right Now Is the Best Time of the Year to Get One"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pKDsF
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Our Black Friday sale just went live \u2014 and it\u2019s the steepest discount offered all year.\n\nRight now, when you buy two "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__i3FZq
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"nanX Spray Guns"}
                  </PlasmicLink__>
                }
                <React.Fragment>{", you get a "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"third one"}
                </span>
                <React.Fragment> </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"free"}
                </span>
                <React.Fragment>
                  {
                    ".\n\nThat means one for you \u2014 and two as gifts for loved ones who care about keeping their homes clean, safe, and fully disinfected.\n\nIt\u2019s the perfect holiday gift for yourself and everyone you love."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ntvcF
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__fVr1Y
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"\ud83d\udc49 Tap Here to Shop the Black Friday Sale"}
                  </PlasmicLink__>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </div>
          <Pdp
            data-plasmic-name={"pdp"}
            data-plasmic-override={overrides.pdp}
            className={classNames("__wab_instance", sty.pdp)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          <Embed
            data-plasmic-name={"metaPixel"}
            data-plasmic-override={overrides.metaPixel}
            className={classNames("__wab_instance", sty.metaPixel)}
            code={
              "\n\n<!-- Meta Pixel Code -->\n<script>\n!function(f,b,e,v,n,t,s)\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\nn.queue=[];t=b.createElement(e);t.async=!0;\nt.src=v;s=b.getElementsByTagName(e)[0];\ns.parentNode.insertBefore(t,s)}(window, document,'script',\n'https://connect.facebook.net/en_US/fbevents.js');\nfbq('init', '819736280774420');\nfbq('track', 'PageView');      // Standard pageview event\n</script>\n<noscript><img height=\"1\" width=\"1\" style=\"display:none\"\nsrc=\"https://www.facebook.com/tr?id=819736280774420&ev=PageView&noscript=1\"\n/></noscript>\n<!-- End Meta Pixel Code -->\n\n"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "announcement", "nav", "pdp", "footer", "metaPixel"],
  announcement: ["announcement"],
  nav: ["nav"],
  pdp: ["pdp"],
  footer: ["footer"],
  metaPixel: ["metaPixel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: typeof Announcement;
  nav: typeof Nav;
  pdp: typeof Pdp;
  footer: typeof Footer;
  metaPixel: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsbreak__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsbreak__VariantsArgs;
    args?: PlasmicNewsbreak__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewsbreak__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewsbreak__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewsbreak__ArgProps,
          internalVariantPropNames: PlasmicNewsbreak__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewsbreak__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewsbreak";
  } else {
    func.displayName = `PlasmicNewsbreak.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsbreak = Object.assign(
  // Top-level PlasmicNewsbreak renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    pdp: makeNodeComponent("pdp"),
    footer: makeNodeComponent("footer"),
    metaPixel: makeNodeComponent("metaPixel"),

    // Metadata about props expected for PlasmicNewsbreak
    internalVariantProps: PlasmicNewsbreak__VariantProps,
    internalArgProps: PlasmicNewsbreak__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Disinfectant Spray Gun | nanX™",
      description:
        "The cordless nanX® Spray Gun eliminates germs on contact—without soaking surfaces or leaving residue. Clean smarter with NanoMist™ technology.",
      ogImageSrc:
        "https://site-assets.plasmic.app/20e233b0acb6b6c934cd365980f2ab84.png",
      canonical: ""
    }
  }
);

export default PlasmicNewsbreak;
/* prettier-ignore-end */
