/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jNtNf7ennmHcnVPPcPauY
// Component: 8MpFhDHD96MB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4jNtNf7ennmHcnVPPcPauY/projectcss
import sty from "./PlasmicPdp.module.css"; // plasmic-import: 8MpFhDHD96MB/css

import BagSvgIcon from "./icons/PlasmicIcon__BagSvg"; // plasmic-import: bSpVB1kOekDy/icon
import StarSvgrepoComSvgIcon from "./icons/PlasmicIcon__StarSvgrepoComSvg"; // plasmic-import: 582rzEIEG-6Y/icon
import DotSvgIcon from "./icons/PlasmicIcon__DotSvg"; // plasmic-import: MOshPqjEhwKE/icon
import CanvasMinusSvgIcon from "./icons/PlasmicIcon__CanvasMinusSvg"; // plasmic-import: gyZOe9j5v6Sj/icon
import CanvasPlusSvgIcon from "./icons/PlasmicIcon__CanvasPlusSvg"; // plasmic-import: ggHb2k1x_-ZC/icon
import FacebookSvgSvgIcon from "./icons/PlasmicIcon__FacebookSvgSvg"; // plasmic-import: P2BABYKb7JKO/icon
import InstagramSvgrepoComSvgIcon from "./icons/PlasmicIcon__InstagramSvgrepoComSvg"; // plasmic-import: V5aco-ZWxhZB/icon

createPlasmicElementProxy;

export type PlasmicPdp__VariantMembers = {};
export type PlasmicPdp__VariantsArgs = {};
type VariantPropType = keyof PlasmicPdp__VariantsArgs;
export const PlasmicPdp__VariantProps = new Array<VariantPropType>();

export type PlasmicPdp__ArgsType = {};
type ArgPropType = keyof PlasmicPdp__ArgsType;
export const PlasmicPdp__ArgProps = new Array<ArgPropType>();

export type PlasmicPdp__OverridesType = {
  root?: Flex__<"div">;
  announcement?: Flex__<"div">;
  nav?: Flex__<"div">;
  body?: Flex__<"div">;
  desktopImages2?: Flex__<"div">;
  mobileImages2?: Flex__<"div">;
  options?: Flex__<"div">;
  _1Unselected?: Flex__<"div">;
  _1Selected?: Flex__<"div">;
  _2Selected?: Flex__<"div">;
  _2Unselected?: Flex__<"div">;
  _3Unselected?: Flex__<"div">;
  _3Selected?: Flex__<"div">;
  divider1?: Flex__<"div">;
  divider2?: Flex__<"div">;
};

export interface DefaultPdpProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPdp__RenderFunc(props: {
  variants: PlasmicPdp__VariantsArgs;
  args: PlasmicPdp__ArgsType;
  overrides: PlasmicPdp__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selected",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 2
      },
      {
        path: "dropdown",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"announcement"}
        data-plasmic-override={overrides.announcement}
        className={classNames(projectcss.all, sty.announcement)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__hkjHb
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700 }}
            >
              {"Black Friday Deal:"}
            </span>
            <React.Fragment>{" Buy 2, Get 1 Free"}</React.Fragment>
          </React.Fragment>
        </div>
      </div>
      <div
        data-plasmic-name={"nav"}
        data-plasmic-override={overrides.nav}
        className={classNames(projectcss.all, sty.nav)}
      >
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__hhdR1)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100px"}
          loading={"eager"}
          src={{
            src: "/plasmic/nan_x/images/nanXLogoSvg2.svg",
            fullWidth: 356,
            fullHeight: 76,
            aspectRatio: undefined
          }}
        />

        <div className={classNames(projectcss.all, sty.freeBox__lb8Vs)} />

        <BagSvgIcon
          className={classNames(projectcss.all, sty.svg__c7Ngw)}
          role={"img"}
        />
      </div>
      <div
        data-plasmic-name={"body"}
        data-plasmic-override={overrides.body}
        className={classNames(projectcss.all, sty.body)}
      >
        <div
          data-plasmic-name={"desktopImages2"}
          data-plasmic-override={overrides.desktopImages2}
          className={classNames(projectcss.all, sty.desktopImages2)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__sumMf)}
            displayHeight={"518px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"eager"}
            src={{
              src: "/plasmic/nan_x/images/nanX2Jpg.jpg",
              fullWidth: 1024,
              fullHeight: 1024,
              aspectRatio: undefined
            }}
          />

          <div className={classNames(projectcss.all, sty.freeBox__gov6S)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__gqucw)}
              displayHeight={"225px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanX3Jpg.jpg",
                fullWidth: 1500,
                fullHeight: 1500,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___9JgWa)}
              displayHeight={"225px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanX1Png.png",
                fullWidth: 1024,
                fullHeight: 1536,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
        <div
          data-plasmic-name={"mobileImages2"}
          data-plasmic-override={overrides.mobileImages2}
          className={classNames(projectcss.all, sty.mobileImages2)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__r6Bmp)}
            displayHeight={"225px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"310px"}
            loading={"eager"}
            src={{
              src: "/plasmic/nan_x/images/nanX2Jpg.jpg",
              fullWidth: 1024,
              fullHeight: 1024,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__ilyH2)}
            displayHeight={"225px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"310px"}
            loading={"eager"}
            src={{
              src: "/plasmic/nan_x/images/nanX3Jpg.jpg",
              fullWidth: 1500,
              fullHeight: 1500,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__rLivj)}
            displayHeight={"225px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"310px"}
            loading={"eager"}
            src={{
              src: "/plasmic/nan_x/images/nanX1Png.png",
              fullWidth: 1024,
              fullHeight: 1536,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__fjoc)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yyvoy
            )}
          >
            {"nanX\u2122 Disinfectant Spray Gun"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__c5HNx)}>
            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__ub4N3)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__sfaIj)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg___4ZNHz)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__ir8Qr)}
              role={"img"}
            />

            <StarSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__idMiz)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__znWgp
              )}
            >
              {"4.8"}
            </div>
            <DotSvgIcon
              className={classNames(projectcss.all, sty.svg__yIdkC)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ka8Sr
              )}
            >
              {"732 Reviews"}
            </div>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cay0F
            )}
          >
            {
              "The nanX\u00ae Spray Gun sanitizes any space in seconds. It eliminates germs on contact\u2014without soaking surfaces or leaving residue."
            }
          </div>
          <div
            data-plasmic-name={"options"}
            data-plasmic-override={overrides.options}
            className={classNames(projectcss.all, sty.options)}
          >
            {(() => {
              try {
                return $state.selected != 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_1Unselected"}
                data-plasmic-override={overrides._1Unselected}
                className={classNames(projectcss.all, sty._1Unselected)}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateSelected"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["selected"]
                          },
                          operation: 0,
                          value: 1
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSelected"] != null &&
                    typeof $steps["updateSelected"] === "object" &&
                    typeof $steps["updateSelected"].then === "function"
                  ) {
                    $steps["updateSelected"] = await $steps["updateSelected"];
                  }
                }}
              >
                <div className={classNames(projectcss.all, sty.freeBox__xgYeB)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9XNdH)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uOjB8)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2Pywz)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xvO3Z)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oiZkc
                        )}
                      >
                        {"1 Spray Gun"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ehpen
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ePqtu
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kYgL6
                      )}
                    >
                      {"Plus $4.95 Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ukjoM)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__so13X)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tJ927
                        )}
                      >
                        {"Save $10.00"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nJoof
                      )}
                    >
                      {"$54.90"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4BiwZ
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$64.90"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.selected == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_1Selected"}
                data-plasmic-override={overrides._1Selected}
                className={classNames(projectcss.all, sty._1Selected)}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateSelected"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["selected"]
                          },
                          operation: 0,
                          value: 1
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSelected"] != null &&
                    typeof $steps["updateSelected"] === "object" &&
                    typeof $steps["updateSelected"].then === "function"
                  ) {
                    $steps["updateSelected"] = await $steps["updateSelected"];
                  }
                }}
              >
                <div className={classNames(projectcss.all, sty.freeBox__bZahs)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iwqgq)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yF80Q)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oWrZu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jhe9R)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uwNgV
                        )}
                      >
                        {"1 Spray Gun"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___8IoAc
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4GswV
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mVaHk
                      )}
                    >
                      {"Plus $4.95 Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mZv8E)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tads2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h968R
                        )}
                      >
                        {"Save $10.00"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wkEsT
                      )}
                    >
                      {"$54.90"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__avtu
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$64.90"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.selected == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_2Selected"}
                data-plasmic-override={overrides._2Selected}
                className={classNames(projectcss.all, sty._2Selected)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qelh1)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uOiBa)}
                  >
                    {(() => {
                      try {
                        return $state.selected == 2;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pTkNz
                        )}
                      />
                    ) : null}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__f675J)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xmhYd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__camA
                        )}
                      >
                        {"Buy 2, Get 1 Free"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1Orfj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iPvP2
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5KfUy
                      )}
                    >
                      {"Plus Free Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qinHl)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___94M8N
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mEsN9
                        )}
                      >
                        {"Save $84.90"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zMm4V
                      )}
                    >
                      {"$109.80"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qGkYw
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$194.70"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.selected != 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_2Unselected"}
                data-plasmic-override={overrides._2Unselected}
                className={classNames(projectcss.all, sty._2Unselected)}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateSelected"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["selected"]
                          },
                          operation: 0,
                          value: 2
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSelected"] != null &&
                    typeof $steps["updateSelected"] === "object" &&
                    typeof $steps["updateSelected"].then === "function"
                  ) {
                    $steps["updateSelected"] = await $steps["updateSelected"];
                  }
                }}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___8QuHt)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hFyiy)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gu09R)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nJXba)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nIcvG)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bwZxM
                        )}
                      >
                        {"Buy 2, Get 1 Free"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zjVfb
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zf2B
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ljhCd
                      )}
                    >
                      {"Plus Free Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0GLbS)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ifMyi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tlH2M
                        )}
                      >
                        {"Save $84.90"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pg1Sp
                      )}
                    >
                      {"$109.80"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k58X7
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$194.70"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.selected != 3;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_3Unselected"}
                data-plasmic-override={overrides._3Unselected}
                className={classNames(projectcss.all, sty._3Unselected)}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateSelected"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["selected"]
                          },
                          operation: 0,
                          value: 3
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSelected"] != null &&
                    typeof $steps["updateSelected"] === "object" &&
                    typeof $steps["updateSelected"].then === "function"
                  ) {
                    $steps["updateSelected"] = await $steps["updateSelected"];
                  }
                }}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qd8T0)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__i2D9O)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mrtwg)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__igKfS)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__memTa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__z1CUs
                        )}
                      >
                        {"Buy 3, Get 2 Free"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___12Pgu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lj61
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__scTy6
                      )}
                    >
                      {"Plus Free Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2OYew)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pmPx2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__idMaQ
                        )}
                      >
                        {"Save $159.80"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ydUwr
                      )}
                    >
                      {"$164.70"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gVhQv
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$324.50"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.selected == 3;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"_3Selected"}
                data-plasmic-override={overrides._3Selected}
                className={classNames(projectcss.all, sty._3Selected)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__nrSmk)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nwsoc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__s5Xvq)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xZzxE)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jOxvq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Vhfw
                        )}
                      >
                        {"Buy 3, Get 2 Free"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jKft7
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cVXp
                          )}
                        >
                          {"Save $59.99"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0KrKw
                      )}
                    >
                      {"Plus Free Shipping"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rix8V)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jCtgO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__omaxJ
                        )}
                      >
                        {"Save $159.80"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g7KnU
                      )}
                    >
                      {"$164.70"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uctg4
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "line-through" }}
                        >
                          {"$324.50"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            <div
              className={classNames(projectcss.all, sty.freeBox__ow0B)}
              onClick={async event => {
                const $steps = {};

                $steps["checkoutPixel"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return (() => {
                            const fbpixel = document.createElement("script");
                            fbpixel.textContent = `
  console.log('Facebook Pixel script is about to run...');
  if (typeof fbq === 'function') {
    fbq('track', 'InitiateCheckout');
    console.log('Facebook Pixel InitiateCheckout event fired successfully.');
  } else {
    console.warn('fbq is not defined — Meta Pixel may not be loaded.');
  }
`;
                            return document.body.appendChild(fbpixel);
                          })();
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["checkoutPixel"] != null &&
                  typeof $steps["checkoutPixel"] === "object" &&
                  typeof $steps["checkoutPixel"].then === "function"
                ) {
                  $steps["checkoutPixel"] = await $steps["checkoutPixel"];
                }

                $steps["_1"] =
                  $state.selected == 1
                    ? (() => {
                        const actionArgs = {
                          destination:
                            "https://buy.stripe.com/8x23cu1JY7QtgqegBReME00?prefilled_promo_code=BlackFriday10"
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps["_1"] != null &&
                  typeof $steps["_1"] === "object" &&
                  typeof $steps["_1"].then === "function"
                ) {
                  $steps["_1"] = await $steps["_1"];
                }

                $steps["_2"] =
                  $state.selected == 2
                    ? (() => {
                        const actionArgs = {
                          destination:
                            "https://buy.stripe.com/00w7sK60eeeR3Ds5XdeME01?prefilled_promo_code=BlackFriday"
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps["_2"] != null &&
                  typeof $steps["_2"] === "object" &&
                  typeof $steps["_2"].then === "function"
                ) {
                  $steps["_2"] = await $steps["_2"];
                }

                $steps["_3"] =
                  $state.selected == 3
                    ? (() => {
                        const actionArgs = {
                          destination:
                            "https://buy.stripe.com/7sY7sKfAOdaN8XMfxNeME02?prefilled_promo_code=BlackFriday"
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps["_3"] != null &&
                  typeof $steps["_3"] === "object" &&
                  typeof $steps["_3"].then === "function"
                ) {
                  $steps["_3"] = await $steps["_3"];
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__w7P4Y
                )}
              >
                {"Order Now"}
              </div>
            </div>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ts6Cp
            )}
          >
            {"30-day money back guarantee."}
          </div>
          <div
            data-plasmic-name={"divider1"}
            data-plasmic-override={overrides.divider1}
            className={classNames(projectcss.all, sty.divider1)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__vvmSd)}>
            <div className={classNames(projectcss.all, sty.freeBox___3KwKj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yDaKt
                )}
              >
                {"Benefits"}
              </div>
              {(() => {
                try {
                  return $state.dropdown == 1;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <CanvasMinusSvgIcon
                  className={classNames(projectcss.all, sty.svg__vrXJh)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateDropdown"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["dropdown"]
                            },
                            operation: 0,
                            value: 0
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateDropdown"] != null &&
                      typeof $steps["updateDropdown"] === "object" &&
                      typeof $steps["updateDropdown"].then === "function"
                    ) {
                      $steps["updateDropdown"] = await $steps["updateDropdown"];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
              {(() => {
                try {
                  return $state.dropdown != 1;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <CanvasPlusSvgIcon
                  className={classNames(projectcss.all, sty.svg___9Jjmn)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateDropdown"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["dropdown"]
                            },
                            operation: 0,
                            value: 1
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateDropdown"] != null &&
                      typeof $steps["updateDropdown"] === "object" &&
                      typeof $steps["updateDropdown"].then === "function"
                    ) {
                      $steps["updateDropdown"] = await $steps["updateDropdown"];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
            </div>
            {(() => {
              try {
                return $state.dropdown == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__fQcS)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__dmB0)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s4XBx
                  )}
                >
                  {"Disinfects rooms, surfaces, and fabrics in seconds"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__a6AwW)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__kw18X)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k9Lhx
                  )}
                >
                  {"Covers large areas residue-free NanoMist\u2122"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__xNPa)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg___0VU8)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zgKuy
                  )}
                >
                  {"Cordless and rechargeable for portability"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__uWhEl)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__ibX7A)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eThzx
                  )}
                >
                  {"Safe for electronics, upholstery, and high-touch areas"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__oynct)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3IKdz
                  )}
                >
                  {"View Clinical Trials \u2192"}
                </div>
              </div>
            ) : null}
          </div>
          <div
            data-plasmic-name={"divider2"}
            data-plasmic-override={overrides.divider2}
            className={classNames(projectcss.all, sty.divider2)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__iA2Kh)}>
            <div className={classNames(projectcss.all, sty.freeBox__pyReB)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kRrg2
                )}
              >
                {"Features & Specs"}
              </div>
              {(() => {
                try {
                  return $state.dropdown == 2;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <CanvasMinusSvgIcon
                  className={classNames(projectcss.all, sty.svg__x3Oaq)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateDropdown"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["dropdown"]
                            },
                            operation: 0,
                            value: 0
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateDropdown"] != null &&
                      typeof $steps["updateDropdown"] === "object" &&
                      typeof $steps["updateDropdown"].then === "function"
                    ) {
                      $steps["updateDropdown"] = await $steps["updateDropdown"];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
              {(() => {
                try {
                  return $state.dropdown != 2;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <CanvasPlusSvgIcon
                  className={classNames(projectcss.all, sty.svg__ebyEy)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateDropdown"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["dropdown"]
                            },
                            operation: 0,
                            value: 2
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateDropdown"] != null &&
                      typeof $steps["updateDropdown"] === "object" &&
                      typeof $steps["updateDropdown"].then === "function"
                    ) {
                      $steps["updateDropdown"] = await $steps["updateDropdown"];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
            </div>
            {(() => {
              try {
                return $state.dropdown == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__duhI)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__wh91E)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gjtGj
                  )}
                >
                  {"NanoMist\u2122 Spray: Complete surface coverage"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__dc3U6)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__xflXl)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mBcSj
                  )}
                >
                  {"Blue LED Beam: Illuminates and targets germs"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox___2RJ9M)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg___1JoFu)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lXzmu
                  )}
                >
                  {"USB-C Charging: Rapid fast rechargeing"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__dmcDk)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__gyJ2M)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__duyh1
                  )}
                >
                  {"13 oz Tank: Sanitizes multiple rooms per fill"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.dropdown == 2;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__jejB)}>
                <DotSvgIcon
                  className={classNames(projectcss.all, sty.svg__bYl9H)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1BdIm
                  )}
                >
                  {"Surface Safe: Works with water-based cleaners"}
                </div>
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__gpv1G)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__frhnU)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "90px"
                  : "112px"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "90px"
                  : "112px"
              }
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanX1Png.png",
                fullWidth: 1024,
                fullHeight: 1536,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__zT6Jy)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5RYsY
                )}
              >
                {"Buy 2, Get 1 Free"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bPcKz
                )}
              >
                {"Gift the original nanX Spray Gun this holiday season!"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fS8Zx)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jLgVc
                  )}
                >
                  {"$109.80"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qkmb4
                  )}
                >
                  {"$194.70"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__sznNh)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return (() => {
                                const fbpixel =
                                  document.createElement("script");
                                fbpixel.textContent = `
  console.log('Facebook Pixel script is about to run...');
  if (typeof fbq === 'function') {
    fbq('track', 'InitiateCheckout');
    console.log('Facebook Pixel InitiateCheckout event fired successfully.');
  } else {
    console.warn('fbq is not defined — Meta Pixel may not be loaded.');
  }
`;
                                return document.body.appendChild(fbpixel);
                              })();
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }

                    $steps["_2"] = true
                      ? (() => {
                          const actionArgs = {
                            destination:
                              "https://buy.stripe.com/00w7sK60eeeR3Ds5XdeME01?prefilled_promo_code=BlackFriday"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["_2"] != null &&
                      typeof $steps["_2"] === "object" &&
                      typeof $steps["_2"].then === "function"
                    ) {
                      $steps["_2"] = await $steps["_2"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dndmi
                    )}
                  >
                    {"Order"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___7U6QT)}>
        <div className={classNames(projectcss.all, sty.freeBox__j3OPa)}>
          <div className={classNames(projectcss.all, sty.freeBox___5Khyo)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__tox2S)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100px"}
              loading={"eager"}
              src={{
                src: "/plasmic/nan_x/images/nanXLogoLightSvg.svg",
                fullWidth: 356,
                fullHeight: 76,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vaZdp
              )}
            >
              {"Pioneering a cleaner world with NanoMist\u2122 technology."}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__lrtx1)}>
              <FacebookSvgSvgIcon
                className={classNames(projectcss.all, sty.svg__l97E)}
                role={"img"}
              />

              <InstagramSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__ujAgo)}
                role={"img"}
              />
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__wctgH)}>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__fnT3D
            )}
            component={Link}
            platform={"nextjs"}
          >
            {"Privacy Policy"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___9DL7U
            )}
            component={Link}
            platform={"nextjs"}
          >
            {"Terms of Service"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__baXc4
            )}
            component={Link}
            platform={"nextjs"}
          >
            {"Return Policy"}
          </PlasmicLink__>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__t0RNb)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__aQEz
            )}
          >
            {"@ 2025 nanX"}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "announcement",
    "nav",
    "body",
    "desktopImages2",
    "mobileImages2",
    "options",
    "_1Unselected",
    "_1Selected",
    "_2Selected",
    "_2Unselected",
    "_3Unselected",
    "_3Selected",
    "divider1",
    "divider2"
  ],
  announcement: ["announcement"],
  nav: ["nav"],
  body: [
    "body",
    "desktopImages2",
    "mobileImages2",
    "options",
    "_1Unselected",
    "_1Selected",
    "_2Selected",
    "_2Unselected",
    "_3Unselected",
    "_3Selected",
    "divider1",
    "divider2"
  ],
  desktopImages2: ["desktopImages2"],
  mobileImages2: ["mobileImages2"],
  options: [
    "options",
    "_1Unselected",
    "_1Selected",
    "_2Selected",
    "_2Unselected",
    "_3Unselected",
    "_3Selected"
  ],
  _1Unselected: ["_1Unselected"],
  _1Selected: ["_1Selected"],
  _2Selected: ["_2Selected"],
  _2Unselected: ["_2Unselected"],
  _3Unselected: ["_3Unselected"],
  _3Selected: ["_3Selected"],
  divider1: ["divider1"],
  divider2: ["divider2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  announcement: "div";
  nav: "div";
  body: "div";
  desktopImages2: "div";
  mobileImages2: "div";
  options: "div";
  _1Unselected: "div";
  _1Selected: "div";
  _2Selected: "div";
  _2Unselected: "div";
  _3Unselected: "div";
  _3Selected: "div";
  divider1: "div";
  divider2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPdp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPdp__VariantsArgs;
    args?: PlasmicPdp__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPdp__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPdp__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPdp__ArgProps,
          internalVariantPropNames: PlasmicPdp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPdp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPdp";
  } else {
    func.displayName = `PlasmicPdp.${nodeName}`;
  }
  return func;
}

export const PlasmicPdp = Object.assign(
  // Top-level PlasmicPdp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    announcement: makeNodeComponent("announcement"),
    nav: makeNodeComponent("nav"),
    body: makeNodeComponent("body"),
    desktopImages2: makeNodeComponent("desktopImages2"),
    mobileImages2: makeNodeComponent("mobileImages2"),
    options: makeNodeComponent("options"),
    _1Unselected: makeNodeComponent("_1Unselected"),
    _1Selected: makeNodeComponent("_1Selected"),
    _2Selected: makeNodeComponent("_2Selected"),
    _2Unselected: makeNodeComponent("_2Unselected"),
    _3Unselected: makeNodeComponent("_3Unselected"),
    _3Selected: makeNodeComponent("_3Selected"),
    divider1: makeNodeComponent("divider1"),
    divider2: makeNodeComponent("divider2"),

    // Metadata about props expected for PlasmicPdp
    internalVariantProps: PlasmicPdp__VariantProps,
    internalArgProps: PlasmicPdp__ArgProps
  }
);

export default PlasmicPdp;
/* prettier-ignore-end */
